
hostname: "192.168.1.91"
database: "postgres"
username: "postgres"
pwd: "root"
port: "5432"

twilio_server:
  account_sid: "xxxxxx"         # your twilio sid
  auth_token: "xxxxx"           # your twilio token
  from_number: "+1xxxxxxxxx"    # your twilio number
  to_number: "+90blahblahblah"  # the operations center number

graph:
  A1:
  - - A7
    - 0.4
  - - A12
    - 0.1
  - - A4
    - 0.1
  - - A2
    - 0.1
  A2:
  - - A1
    - 0.1
  - - A9
    - 0.1
  A3:
  - - A8
    - 0.1
  A4:
  - - A8
    - 0.1
  - - A1
    - 0.1
  - - A11
    - 0.1
  - - A6
    - 0.1
  A5:
  - - A7
    - 0.1
  A6:
  - - A10
    - 0.1
  - - A2
    - 0.1
  - - A4
    - 0.1
  A7:
  - - A12
    - 0.1
  - - A1
    - 0.1
  - - A5
    - 0.1
  A8:
  - - A3
    - 0.1
  - - A4
    - 0.1
  - - A11
    - 0.1
  A9:
  - - A2
    - 0.1
  A10:
  - - A6
    - 0.1
  A11:
  - - A4
    - 0.1
  - - A8
    - 0.1
  - - A12
    - 0.1
  A12:
  - - A11
    - 0.1
  - - A7
    - 0.1
  - - A1
    - 0.1

itinerary:
- coordinate:
  - -0.55
  - -0.55
  - -0.194
  - 0.98
  description: checkpoint
  fleet_id: kullar
  loc_id: A1

- coordinate:
  - 0.55
  - -0.55
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  loc_id: A2

- coordinate:
  - 0.5
  - 1.7
  - -0.097
  - 0.995
  description: station_dock
  fleet_id: kullar
  loc_id: A3 ########

- coordinate:
  - -0.53
  - 0.53
  - -0.097
  - 0.995
  description: checkpoint
  fleet_id: kullar
  loc_id: A4

- coordinate:
  - 0.5
  - -1.8
  - -0.097
  - 0.995
  description: station_dock
  fleet_id: kullar
  loc_id: A5 ########

- coordinate:
  - 0.53
  - 0.53
  - -0.695
  - 0.718
  description: checkpoint
  fleet_id: kullar
  loc_id: A6

- coordinate:
  - -0.5
  - -1.75
  - -0.695
  - 0.718
  description: checkpoint
  fleet_id: kullar
  loc_id: A7

- coordinate:
  - -0.5
  - 1.8
  - 0.923
  - 0.004
  description: checkpoint
  fleet_id: kullar
  loc_id: A8

- coordinate:
  - 1.8
  - -0.57
  - 0.923
  - 0.004
  description: charge_dock
  fleet_id: kullar
  loc_id: A9 ############

- coordinate:
  - 1.8
  - 0.49
  - -0.695
  - 0.718
  description: home_dock
  fleet_id: kullar
  loc_id: A10 ##########

- coordinate:
  - -1.7
  - 0.52
  - -0.999
  - 0.006
  description: checkpoint
  fleet_id: kullar
  loc_id: A11

- coordinate:
  - -1.5
  - -1.3
  - -0.999
  - 0.006
  description: checkpoint
  fleet_id: kullar
  loc_id: A12 ######

organization: ROBO
programmer: Azeez Adebayo
project_date: 2022
website: https://www.robo.com.tr/
